### ISSUE TITLE
Incorrent entry (main, types, module) in package.json. ref and style are required

### ISSUE THREAD

**Issue by AndreiTelteu** [TiagoCavalcante/solidjs-div-100vh#2]
Hi !
I want to report two issues: 

### Problem 1: 
If i try to import the component as in the example from the README.md I get error:

```jsx
import Div100vh from "solidjs-div-100vh"
```

> ERROR: [plugin:vite:import-analysis] Failed to resolve entry for package "solidjs-div-100vh". The package may have incorrect main/module/exports specified in its package.json.

I have to import it like this to work

```jsx
import Div100vh from "solidjs-div-100vh/packages/solidjs-div-100vh";
```

I think a fix is to prepend `packages/solidjs-div-100vh/` at the begining of main, types and module in the main package.json file
https://github.com/TiagoCavalcante/solidjs-div-100vh/blob/main/package.json#L6
```json
  "main": "packages/solidjs-div-100vh/dist/index.cjs.js",
```

### Problem 2:
 The type for Div100vh component has ref and style as required props.
If i try to use `<Div100vh>` simple without any props I get error:

> Type '{ children: Element; }' is missing the following properties from type '{ ref: Element; style: CSSProperties; }': ref, style

Solution here is to make them optional: 
https://github.com/TiagoCavalcante/solidjs-div-100vh/blob/main/packages/solidjs-div-100vh/src/index.tsx#L13
```ts
    ref?: JSX.Element
    style?: JSX.CSSProperties
```

**Comment by TiagoCavalcante** [comment]
Hi @AndreiTelteu, thanks for using the library and creating the issue!

I believe that PR #3 has fixed both problems, but if they didn't you can re-open this or create a new issue

**Comment by AndreiTelteu** [comment]
@TiagoCavalcante Works perfectly !
Thank you for creating this plugin !

**Comment by TiagoCavalcante** [comment]
> @TiagoCavalcante Works perfectly !
> Thank you for creating this plugin !

@AndreiTelteu I'm happy you like it!
Have a happy new year!
